# Generated by Django 3.0.7 on 2020-06-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200617_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
    ]
