# Generated by Django 3.0.7 on 2020-06-17 16:58

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200617_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='cnpj',
            field=localflavor.br.models.BRCNPJField(max_length=18),
        ),
    ]
