# Generated by Django 3.0.7 on 2020-06-17 17:29

import bradoo.core.validators
from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200617_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='cnpj',
            field=localflavor.br.models.BRCNPJField(max_length=18, validators=[bradoo.core.validators.validate_cnpj]),
        ),
    ]
