# Generated by Django 3.0.7 on 2020-06-19 15:10

import bradoo.core.validators
from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200617_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='cnpj',
            field=localflavor.br.models.BRCNPJField(max_length=18, unique=True, validators=[bradoo.core.validators.validate_cnpj]),
        ),
    ]
